
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rocketmq.apache.org
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - brokers/finalizers
  verbs:
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - console
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - console/finalizers
  verbs:
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - console/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservice
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservice/finalizers
  verbs:
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - nameservice/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - topictransfer
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rocketmq.apache.org
  resources:
  - topictransfer/finalizers
  verbs:
  - update
- apiGroups:
  - rocketmq.apache.org
  resources:
  - topictransfer/status
  verbs:
  - get
  - patch
  - update
